- hosts: windows
  tasks:
    - name: uninstall the crowdstrike falcon sensor
      ansible.builtin.include_module:
        name: crowdstrike.falcon.falcon_uninstall
#      vars:
#        falcon_windows_uninstall_args:
#           /norestart
