- name: Uninstall Crowdstrike Falcon and remediate 2024-07-19 incident
  hosts: windows
  tasks:
    - name: Uninstall the crowdstrike falcon sensor
      ansible.builtin.include_role:
        name: crowdstrike.falcon.falcon_uninstall
